"""Generate reproducible Python scripts from applied cleaning actions."""

from __future__ import annotations

from typing import Any

import pandas as pd


def generate_script(
    source_path: str,
    output_path: str,
    actions: list[dict[str, Any]],
    log: list[dict[str, Any]] | None = None,
) -> str:
    """Build a standalone Python script that reproduces the cleaning pipeline."""
    lines = [
        '"""Reproducible cleaning script generated by CSV Data Cleaning Assistant."""',
        "",
        "import pandas as pd",
        "",
        f'SOURCE_PATH = "{source_path}"',
        f'OUTPUT_PATH = "{output_path}"',
        "",
        "",
        "def load_data(path: str) -> pd.DataFrame:",
        '    return pd.read_csv(path)',
        "",
        "",
        "def clean_data(df: pd.DataFrame) -> pd.DataFrame:",
        "    result = df.copy()",
        "",
    ]

    for action in actions:
        lines.extend(_code_lines_for_action(action))
        lines.append("")

    lines.extend(
        [
            "    return result",
            "",
            "",
            "def main() -> None:",
            "    df = load_data(SOURCE_PATH)",
            '    print(f"Loaded {len(df):,} rows, {len(df.columns)} columns")',
            "    cleaned = clean_data(df)",
            '    print(f"Cleaned {len(cleaned):,} rows, {len(cleaned.columns)} columns")',
            "    cleaned.to_csv(OUTPUT_PATH, index=False)",
            '    print(f"Saved to {OUTPUT_PATH}")',
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
            "",
        ]
    )

    if log:
        lines.insert(
            6,
            "# Applied steps:\n"
            + "".join(f"#   - {entry['label']} ({entry['action_id']})\n" for entry in log),
        )

    return "\n".join(lines)


def _code_lines_for_action(action: dict[str, Any]) -> list[str]:
    action_type = action["action_type"]
    params = action.get("params", {})
    label = action.get("label", action["id"])
    header = [f"    # {label}"]

    if action_type in ["drop_duplicates_row", "drop_duplicates_ID"]:
        subset = params.get("subset")
        keep = params.get("keep", "first")
        subset_repr = repr(subset)
        return header + [
            f"    result = result.drop_duplicates(subset={subset_repr}, keep={keep!r}).reset_index(drop=True)",
        ]

    if action_type == "drop_na":
        subset = repr(params.get("subset"))
        how = repr(params.get("how", "any"))
        return header + [f"    result = result.dropna(subset={subset}, how={how}).reset_index(drop=True)"]

    if action_type == "fill_na_median":
        col = params["column"]
        strategy = params.get("strategy", "mode")
        if strategy == "median":
            fill_expr = f"result[{col!r}].median()"
        elif strategy == "mean":
            fill_expr = f"result[{col!r}].mean()"
        else:
            fill_expr = f"result[{col!r}].mode(dropna=True).iloc[0]"
        return header + [f"    result[{col!r}] = result[{col!r}].fillna({fill_expr})"]

    # if action_type == "fill_na_stochastic":


    if action_type == "drop_columns":
        cols = params.get("columns", [])
        return header + [f"    result = result.drop(columns={cols!r})"]

    if action_type == "strip_whitespace":
        col = params["column"]
        return header + [
            f"    _na_mask = result[{col!r}].isna()",
            f"    result[{col!r}] = result[{col!r}].astype(str).str.strip()",
            f"    result.loc[_na_mask, {col!r}] = pd.NA",
        ]

    if action_type == "normalize_case":
        col = params["column"]
        case = params.get("case", "title")
        if case == "lower":
            expr = f"result[{col!r}].astype(str).str.lower()"
        elif case == "upper":
            expr = f"result[{col!r}].astype(str).str.upper()"
        else:
            expr = f"result[{col!r}].astype(str).str.title()"
        return header + [
            f"    _na_mask = result[{col!r}].isna()",
            f"    result[{col!r}] = {expr}",
            f"    result.loc[_na_mask, {col!r}] = pd.NA",
        ]

    if action_type == "clip_outliers":
        col = params["column"]
        return header + [
            f"    _valid = result[{col!r}].dropna()",
            "    _q1, _q3 = _valid.quantile(0.25), _valid.quantile(0.75)",
            "    _iqr = _q3 - _q1",
            "    _lower, _upper = _q1 - 1.5 * _iqr, _q3 + 1.5 * _iqr",
            f"    result[{col!r}] = result[{col!r}].clip(lower=_lower, upper=_upper)",
        ]

    if action_type in ["merge_values", "custom_mapping"]:
        col = params["column"]
        mapping = params["mapping"]
        return header + [
            f"  result[{col!r}] = result[{col!r}.replace({mapping!r})",
        ]

    return header + [f"    # Unsupported action: {action_type}"]
