from rapidfuzz import fuzz

print(fuzz.ratio("Male", "male"))
print(fuzz.ratio("Tanzania", "Taznania"))
print(fuzz.ratio("USA", "US"))
print(fuzz.ratio("M", "Male"))
print(fuzz.ratio("Male", "Female"))
print("Partial Ratio:")
print(fuzz.partial_ratio("Male", "male"))
print(fuzz.partial_ratio("Tanzania", "Taznania"))
print(fuzz.partial_ratio("USA", "US"))
print(fuzz.partial_ratio("M", "Male"))
print(fuzz.partial_ratio("Male", "Female"))
print("Token Sort Ratio")
print(fuzz.token_sort_ratio("Male", "male"))
print(fuzz.token_sort_ratio("Tanzania", "Taznania"))
print(fuzz.token_sort_ratio("USA", "US"))
print(fuzz.token_sort_ratio("M", "Male"))
print(fuzz.token_sort_ratio("Male", "Female"))